### ISSUE TITLE
Doesn't seem to function with Encrypted Google search results.

### ISSUE THREAD

**Issue by gutzsant** [LittleLightLittleFire/link-fixer#1]
For some reason, it doesn't work with https://encrypted.google.com/ . This seems to apply only to regular search results since image results with Encrypted Google have the link fixed.

**Comment by LittleLightLittleFire** [comment]
encrypted.google.com (and images) is slightly different. I currently have a patch that fixes normal search. I'll update the extension once I fix both of them.

encrypted.google.com image search is a bit annoying to deal with since it places the image links inside iframes.

**Comment by gutzsant** [comment]
Google link fixer works fine with encrypted.google.com image search, both with the "Visit page" and "View image" links. It's only with regular web results that the issue occurs. Sorry for not being clear enough about that.

**Comment by LittleLightLittleFire** [comment]
Fixed with https://github.com/LittleLightLittleFire/link-fixer/commit/4c0eb9727a6ad853de5a3272502d6e05db4fa72e

Chrome store has also been updated with the newer version.
